// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcexnFzCXAgd52CUi3OcLrO36yYpNFTz4',
    appId: '1:1093443293754:web:4bf8a57897584148f29b03',
    messagingSenderId: '1093443293754',
    projectId: 'flutter-final-app-bcd9d',
    authDomain: 'flutter-final-app-bcd9d.firebaseapp.com',
    databaseURL: 'https://flutter-final-app-bcd9d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-final-app-bcd9d.appspot.com',
    measurementId: 'G-ZLD4Z0Y5BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLyJJsRr_DmknBSKqVU7k_uZca5QB6ugA',
    appId: '1:1093443293754:android:64eed1bf042a73f0f29b03',
    messagingSenderId: '1093443293754',
    projectId: 'flutter-final-app-bcd9d',
    databaseURL: 'https://flutter-final-app-bcd9d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-final-app-bcd9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2kO1xnx3vSkxsAeVCs22Cf3Obxopd9Jo',
    appId: '1:1093443293754:ios:8497407d13adba4cf29b03',
    messagingSenderId: '1093443293754',
    projectId: 'flutter-final-app-bcd9d',
    databaseURL: 'https://flutter-final-app-bcd9d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-final-app-bcd9d.appspot.com',
    iosBundleId: 'com.example.strongChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2kO1xnx3vSkxsAeVCs22Cf3Obxopd9Jo',
    appId: '1:1093443293754:ios:8497407d13adba4cf29b03',
    messagingSenderId: '1093443293754',
    projectId: 'flutter-final-app-bcd9d',
    databaseURL: 'https://flutter-final-app-bcd9d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-final-app-bcd9d.appspot.com',
    iosBundleId: 'com.example.strongChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAziDbyTEhgpHNNJqVXiVEI5nzwf-3s4Zc',
    appId: '1:1093443293754:web:d866244f10c17006f29b03',
    messagingSenderId: '1093443293754',
    projectId: 'flutter-final-app-bcd9d',
    authDomain: 'flutter-final-app-bcd9d.firebaseapp.com',
    databaseURL: 'https://flutter-final-app-bcd9d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-final-app-bcd9d.appspot.com',
    measurementId: 'G-3Z1Z784BPR',
  );
}
